---
title: "About"
date: "2022-08-19"
output: html_fragment
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The BCGcalc Shiny app is a free R-based tool to help calculate Biological
Condition Gradient (BCG) metric and site/sample scores. 

This Shiny app is linked to the BCGcalc and BioMonTools R packages, which were
developed by Erik W. Leppo from Tetra Tech and are available on GitHub (<https://github.com/leppott/ContDataQC> and 
<https://github.com/leppott/BCGcalc>). 

Development of the BCGcalc and BioMonTools R packages have been funded, in part,
by the United States Environmental Protection Agency (EPA) Office of Research and
Development (ORD) as part of a 

**NEEDS work **

larger project to establish Regional
Monitoring Networks (RMNs) for freshwater streams and inland lakes
(USEPA 2016, USEPA 2021; lead EPA scientist: Britta Bierwagen). The RMNs
are a volunteer, collaborative effort in which entities collect
long-term data at targeted sites to detect changes over time.

If you encounter problems with the Shiny app and/or have suggestions on
ways to further improve it, please email Erik
([Erik.Leppo\@tetratech.com](mailto:Erik.Leppo@tetratech.com){.email})
or post your comments on the ContDataSumViz GitHub page
(<https://github.com/leppott/BCGcalc/discussions>). This is an
open-source, collaborative effort and we welcome your feedback.

*Last updated 2022-08-19*
